### ISSUE TITLE
Quite poor landscape support

### ISSUE THREAD

**Issue by atfo** [eslcc/euroschool-app#112]
![image](https://cloud.githubusercontent.com/assets/23322023/26275879/4bb26b0a-3d6b-11e7-952e-1e59822bf9fc.png)
Quite poor landscape support...

**Comment by atfo** [comment]
Check out *orientation-fix* branch.

**Comment by markspolakovs** [comment]
@atfo Seems like it's not pushed properly? (I can't find it in your fork or in the main repo.)

**Comment by markspolakovs** [comment]
Fixed in #114
